### ISSUE TITLE
make legend oriented vertically or horizontally?

### ISSUE THREAD

**Issue by gabegaster** [jgoodall/d3-colorlegend#2]
In the color legend example, all the legends were oriented horizontally. Is it possible to make the legend oriented vertically or is this a default? I couldn't tell from the ReadMe or the example. If it is a default, I'd be happy to add the feature. Thanks -- and cool module.

**Comment by jgoodall** [comment]
Thanks to @loistava for submitting the pull request to implement this; sorry it took so long to merge!
